# Generated by Django 3.1.7 on 2021-03-28 12:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('box_plot_chart_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('ml_project', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='ml.mlproject'))])), ('doughnut_chart_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('ml_project', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='ml.mlproject'))])), ('pca_scatter_plot_chart_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('ml_project', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='ml.mlproject'))])), ('petal_histogram_chart_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('ml_project', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='ml.mlproject'))])), ('roc_curve_chart_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('ml_project', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='ml.mlproject'))])), ('validation_curve_chart_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('ml_project', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='ml.mlproject'))]))], blank=True, null=True),
        ),
    ]
